name: base
channels:
  - plotly
  - cogsci
  - defaults
  - conda-forge
dependencies:
  - tensorflow
  - pylint
  - pydot
  - py-xgboost
  - tabulate
  - plotly
  - gym
  - pyvirtualdisplay
  - box2d-py
  - pygame
  - imageio
  - imageio-ffmpeg